# Generated by Django 4.0.4 on 2022-05-04 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nose_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
