# Generated by Django 4.0.4 on 2022-05-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_first_name_player_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hair_color',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
