# Generated by Django 4.0.4 on 2022-05-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_player_hair_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='body_color',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
