# Generated by Django 4.0.4 on 2022-05-14 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_remove_player_hair_color_remove_player_hair_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairmodel',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hair_id', to='player.player'),
        ),
    ]
