# Generated by Django 4.0.4 on 2022-05-16 20:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_alter_hairmodel_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairmodel',
            name='hair_color',
        ),
        migrations.RemoveField(
            model_name='player',
            name='beard_color',
        ),
        migrations.RemoveField(
            model_name='player',
            name='beard_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='body_color',
        ),
        migrations.RemoveField(
            model_name='player',
            name='clothing_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='eye_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='eyebrow_color',
        ),
        migrations.RemoveField(
            model_name='player',
            name='eyebrow_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='mouth_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nose_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pants_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='shoes_id',
        ),
        migrations.CreateModel(
            name='ShoesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes_id', models.UUIDField(default=uuid.uuid4)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shoes_id', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='PantsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pants_id', models.UUIDField(default=uuid.uuid4)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pants_id', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='NoseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nose_id', models.UUIDField(default=uuid.uuid4)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nose_id', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='MouthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouth_id', models.UUIDField(default=uuid.uuid4)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mouth_id', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='HairColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_color', models.CharField(max_length=10000)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hair_color', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='EyeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_id', models.UUIDField(default=uuid.uuid4)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eye_id', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='EyeBrowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_id', models.UUIDField(default=uuid.uuid4)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eyebrow_id', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='EyeBrowColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_color', models.CharField(max_length=10000)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eyebrow_color', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='ClothingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_id', models.UUIDField(default=uuid.uuid4)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_id', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='BodyColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_id', models.UUIDField(default=uuid.uuid4)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body_color', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='BeardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beard_id', models.UUIDField(default=uuid.uuid4)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beard_id', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='BeardColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beard_color', models.CharField(max_length=10000)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beard_color', to='player.player')),
            ],
        ),
    ]
