# Generated by Django 4.0.4 on 2022-05-16 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_remove_hairmodel_hair_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beardcolormodel',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beard_color', to='player.player'),
        ),
        migrations.AlterField(
            model_name='beardmodel',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beard_id', to='player.player'),
        ),
        migrations.AlterField(
            model_name='bodycolormodel',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_color', to='player.player'),
        ),
        migrations.AlterField(
            model_name='clothingmodel',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_id', to='player.player'),
        ),
        migrations.AlterField(
            model_name='eyebrowcolormodel',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eyebrow_color', to='player.player'),
        ),
        migrations.AlterField(
            model_name='eyebrowmodel',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eyebrow_id', to='player.player'),
        ),
        migrations.AlterField(
            model_name='eyemodel',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_id', to='player.player'),
        ),
        migrations.AlterField(
            model_name='haircolormodel',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hair_color', to='player.player'),
        ),
        migrations.AlterField(
            model_name='hairmodel',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hair_id', to='player.player'),
        ),
        migrations.AlterField(
            model_name='mouthmodel',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouth_id', to='player.player'),
        ),
        migrations.AlterField(
            model_name='nosemodel',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nose_id', to='player.player'),
        ),
        migrations.AlterField(
            model_name='pantsmodel',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pants_id', to='player.player'),
        ),
        migrations.AlterField(
            model_name='shoesmodel',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoes_id', to='player.player'),
        ),
    ]
