# Generated by Django 4.0.4 on 2022-05-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_alter_beardcolormodel_player_alter_beardmodel_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodycolormodel',
            name='eye_id',
        ),
        migrations.AddField(
            model_name='bodycolormodel',
            name='body_color',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
