# Generated by Django 4.0.4 on 2022-05-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_remove_bodycolormodel_eye_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landnft_id', models.TextField(blank=True, null=True, unique=True)),
                ('landnft_image', models.ImageField(upload_to='', verbose_name='images/')),
                ('land_name', models.CharField(max_length=100, null=True)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_id', models.TextField(blank=True, null=True, unique=True)),
                ('nft_image', models.ImageField(upload_to='', verbose_name='images/')),
                ('pet_name', models.CharField(max_length=100, null=True)),
                ('breed', models.IntegerField()),
                ('pet_color', models.CharField(max_length=100, null=True)),
                ('phase', models.IntegerField()),
                ('level', models.IntegerField()),
                ('exp', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='beardmodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='bodycolormodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='clothingmodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='eyebrowcolormodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='eyebrowmodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='eyemodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='haircolormodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='hairmodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='mouthmodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='nosemodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='pantsmodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='shoesmodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='character_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='eyes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.AddField(
            model_name='player',
            name='beard_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='beard_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='body_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='eye',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='eyebrow_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='eyebrow_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='hair_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='hair_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='mouth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pants',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='shirt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='shoes_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='BeardColorModel',
        ),
        migrations.DeleteModel(
            name='BeardModel',
        ),
        migrations.DeleteModel(
            name='BodyColorModel',
        ),
        migrations.DeleteModel(
            name='ClothingModel',
        ),
        migrations.DeleteModel(
            name='EyeBrowColorModel',
        ),
        migrations.DeleteModel(
            name='EyeBrowModel',
        ),
        migrations.DeleteModel(
            name='EyeModel',
        ),
        migrations.DeleteModel(
            name='HairColorModel',
        ),
        migrations.DeleteModel(
            name='HairModel',
        ),
        migrations.DeleteModel(
            name='MouthModel',
        ),
        migrations.DeleteModel(
            name='NoseModel',
        ),
        migrations.DeleteModel(
            name='PantsModel',
        ),
        migrations.DeleteModel(
            name='ShoesModel',
        ),
    ]
